In [335]:
import pandas as pd
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from xgboost import XGBClassifier
import pickle
import joblib

In [336]:
scaler_1h = joblib.load('../src/our_models/scaler_1hour.pkl')
scaler_2h = joblib.load('../src/our_models/scaler_2hour.pkl')
scaler_all = joblib.load('../src/our_models/scaler_all.pkl')

In [337]:
with open('../src/our_models/3_Xgboost_1hour.pkl', 'rb') as f:
    model_1h = pickle.load(f)
with open('../src/our_models/3_Xgboost_2hour.pkl', 'rb') as f:
    model_2h = pickle.load(f)
with open('../src/our_models/3_Xgboost_all.pkl', 'rb') as f:
    model_all = pickle.load(f)

In [338]:
df = pd.read_csv("../data/everyhour_predict/test.csv",sep=";")

In [339]:
df

region_id  day_datetimeEpoch  day_tempmax  day_tempmin  day_temp  \
0            2         1745355600         25.3         12.8      18.7   
1            2         1745355600         25.3         12.8      18.7   
2            2         1745355600         25.3         12.8      18.7   
3            2         1745355600         25.3         12.8      18.7   
4            2         1745355600         25.3         12.8      18.7   
..         ...                ...          ...          ...       ...   
571          1         1745442000         26.8         14.2      20.5   
572          1         1745442000         26.8         14.2      20.5   
573          1         1745442000         26.8         14.2      20.5   
574          1         1745442000         26.8         14.2      20.5   
575          1         1745442000         26.8         14.2      20.5   

     day_dew  day_humidity  day_precip  day_precipcover  day_solarradiation  \
0        4.6          42.2         0.0              0.0               286.2   
1        4.6          42.2         0.0              0.0               286.2   
2        4.6          42.2         0.0              0.0               286.2   
3        4.6          42.2         0.0              0.0               286.2   
4        4.6          42.2         0.0              0.0               286.2   
..       ...           ...         ...              ...                 ...   
571      3.6          35.5         0.0              0.0               229.1   
572      3.6          35.5         0.0              0.0               229.1   
573      3.6          35.5         0.0              0.0               229.1   
574      3.6          35.5         0.0              0.0               229.1   
575      3.6          35.5         0.0              0.0               229.1   

     ...    993    994    995    996   997    998    999  status  ru_holiday  \
0    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
1    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
2    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
3    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
4    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
..   ...    ...    ...    ...    ...   ...    ...    ...     ...         ...   
571  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
572  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
573  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
574  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
575  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   

     ua_holiday  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
571           0  
572           0  
573           0  
574           0  
575           0  

[576 rows x 1040 columns]

In [340]:
X_new = df[df['region_id'] == 21]
X_1 = X_new.iloc[[0]]
X_2 = X_new.iloc[[1]]
X_all = X_new.iloc[2:]
X_all = X_all.drop("status", axis=1)

In [341]:
X_1_scaled = scaler_1h.transform(X_1)
X_2_scaled = scaler_2h.transform(X_2)
X_all_scaled = scaler_all.transform(X_all)

In [342]:
y_pred_1 = model_1h.predict(X_1_scaled)

In [343]:
y_pred_1

array([0])

In [344]:
y_pred_2 = model_2h.predict(X_2_scaled)

In [345]:
y_pred_2

array([0])

In [346]:
y_pred_all = model_all.predict(X_all_scaled)
y_pred_all

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [347]:
df

region_id  day_datetimeEpoch  day_tempmax  day_tempmin  day_temp  \
0            2         1745355600         25.3         12.8      18.7   
1            2         1745355600         25.3         12.8      18.7   
2            2         1745355600         25.3         12.8      18.7   
3            2         1745355600         25.3         12.8      18.7   
4            2         1745355600         25.3         12.8      18.7   
..         ...                ...          ...          ...       ...   
571          1         1745442000         26.8         14.2      20.5   
572          1         1745442000         26.8         14.2      20.5   
573          1         1745442000         26.8         14.2      20.5   
574          1         1745442000         26.8         14.2      20.5   
575          1         1745442000         26.8         14.2      20.5   

     day_dew  day_humidity  day_precip  day_precipcover  day_solarradiation  \
0        4.6          42.2         0.0              0.0               286.2   
1        4.6          42.2         0.0              0.0               286.2   
2        4.6          42.2         0.0              0.0               286.2   
3        4.6          42.2         0.0              0.0               286.2   
4        4.6          42.2         0.0              0.0               286.2   
..       ...           ...         ...              ...                 ...   
571      3.6          35.5         0.0              0.0               229.1   
572      3.6          35.5         0.0              0.0               229.1   
573      3.6          35.5         0.0              0.0               229.1   
574      3.6          35.5         0.0              0.0               229.1   
575      3.6          35.5         0.0              0.0               229.1   

     ...    993    994    995    996   997    998    999  status  ru_holiday  \
0    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
1    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
2    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
3    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
4    ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
..   ...    ...    ...    ...    ...   ...    ...    ...     ...         ...   
571  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
572  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
573  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
574  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   
575  ...  0.697  0.585  0.665  0.689  0.64  0.658  0.803       0           0   

     ua_holiday  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
571           0  
572           0  
573           0  
574           0  
575           0  

[576 rows x 1040 columns]

In [348]:
scaler_1h

StandardScaler()